name: Android CI

on: [push, pull_request]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare thirdparty
        run: bash ./gradlew -b thirdparty_build.gradle downloadAndPatchDjvu downloadAndMakeMupdf
      - name: Build debug APK
        run: bash ./gradlew assembleCi --stacktrace -Porion.CIBuild=true
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: OrionViewer
          path: orion-viewer/build/outputs/apk/**/*.apk
