name: Android CI

on:
  push:
    branches:
      - master
      - dev**
  pull_request:
    branches:
      - master
      - dev**

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare thirdparty
        run: bash ./gradlew -b thirdparty_build.gradle downloadAndPatchDjvu downloadAndMakeMupdf
      - name: Build debug APK
        run: bash ./gradlew assembleCi --stacktrace -Porion.CIBuild=true
      - name: Upload arm7 APK
        uses: actions/upload-artifact@v2
        with:
          name: OrionViewer-arm7-dev-${{github.run_number}}.zip
          path: orion-viewer/build/outputs/apk/arm7/ci/*.apk
      - name: Upload arm64 APK
        uses: actions/upload-artifact@v2
        with:
          name: OrionViewer-arm64-dev-${{github.run_number}}.zip
          path: orion-viewer/build/outputs/apk/arm64/ci/*.apk
      - name: Upload x86 APK
        uses: actions/upload-artifact@v2
        with:
          name: OrionViewer-x86-dev-${{github.run_number}}.zip
          path: orion-viewer/build/outputs/apk/x86/ci/*.apk
      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v2
        with:
          name: OrionViewer-x86_64-dev-${{github.run_number}}.zip
          path: orion-viewer/build/outputs/apk/x86_64/ci/*.apk                   
