name: Android CI

on:
  push:
    branches: 
      - 'master'
  
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - name: Create empty  file
        uses: finnp/create-file-action@1.0.0	
        env:	
          FILE_NAME: "local.${GITHUB_SHA:8}"
          FILE_DATA: ""
