name: Android CI

on:
  push:
    branches: 
      - 'master'
  
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - name: Create empty ${{github.sha:8}}
        uses: finnp/create-file-action@1.0.0	
        env:	
          FILE_NAME: "local.properties"	
          FILE_DATA: ""
