name: Android CI

on:
  push:
    branches: 
      - 'master'
  
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Test-${GITHUB_SHA:8}
          path: orion-viewer/local.properties.sample
